replicaCount: 2

image:
  repository: 123456789.dkr.ecr.us-west-2.amazonaws.com/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.dev.com
      paths:
        - path: /
          pathType: Prefix
  tls: [] # we’ll add TLS later
