replicaCount: 2

image:
  repository: 123456789.dkr.ecr.us-west-2.amazonaws.com/myapp
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8085

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: false
